### ISSUE TITLE
Lier les commits au compte Github des auteurs

### ISSUE THREAD

**Issue by clementbrizard** [impactometre/impactometre-back#2]

**Comment by mglorion** [comment]
Il m'a suffit de vérifier/associer mon email etu à mon profil [dans les paramètres](https://github.com/settings/emails) GitHub pour corriger cela, est-ce vous l'avez fait ? Cela serait moins périlleux que de republier tous vos commits !

**Comment by clementbrizard** [comment]
> Il m'a suffit de vérifier/associer mon email etu à mon profil [dans les paramètres](https://github.com/settings/emails) GitHub pour corriger cela, est-ce vous l'avez fait ? Cela serait moins périlleux que de republier tous vos commits !

Bonne idée en effet ! J'ai testé, maintenant j'apparais bien comme auteur des commits (ex : https://github.com/impactometre/impactometre-back/commit/67f698afbdebd15f60fc8d1ffc849e0e1caf7fd8), mais pas comme contributeur, étrange. Apparemment il faut laisser passer 24h, mais je pense que là elles sont passées.

**Comment by clementbrizard** [comment]
J'ai ouvert un [ticket](https://support.github.com/ticket/1003531) chez le support de Github.

**Comment by clementbrizard** [comment]
Ils ont réglé le pb en lançant un job de recalcul des contributions pour ce repo, ça a marché pour moi parce que j'avais lié mon adresse UTC. 

@auberanger et @ValLG, est-ce que vous pouvez essayer d'ajouter la ou les adresses avec lesquelles vous avez fait les commits dans votre profil Github ? On va voir si ça met à jour les contributions, ou si je dois de nouveau faire une demande au support.

Je ferme cette issue vu qu'elle n'a finalement pas à être réglée en réécrivant l'historique.
