### ISSUE TITLE
Résultats étonnants - vérification calculs trajets

### ISSUE THREAD

**Issue by auberanger** [impactometre/impactometre-back#6]
En faisant des tests de scénarios, on obtient un résultat assez étonnant : en prenant les scénarios de l'article, si on modifie pour le scénario C le nombre de km en voiture électrique de 2 à 20km, les impacts du scénario augmentent de façon assez surprenante (cf. captures d'écran). 

C'est possible que ce soit un résultat normal mais il faut dans tous les cas qu'on fasse une vérification des calculs de trajet avec la question des personne-kilomètres (cc @clementbrizard @ValLG)

![scenari_article_impactometre_web](https://user-images.githubusercontent.com/43744761/107261978-48fe2b00-6a40-11eb-81c1-f474a8531b35.png)
![scenari_article_impactometre_web_bis_chelou](https://user-images.githubusercontent.com/43744761/107261985-4bf91b80-6a40-11eb-8d0f-f93742d3de1a.png)

En attente de #14

**Comment by ValLG** [comment]
Ces résultats sont tout à fait normaux. Les impacts des voitures thermique et électrique sont de même ordre de grandeur, et il y a en moyenne un ordre de grandeur en moins pour les autres moyens de transport (bus, train, vélo).
